export const AUTH_REQUEST = '/auth/REQUEST';
export const AUTH_SUCCESS = '/auth/SUCCESS';
export const AUTH_ERROR = '/auth/ERROR';

export const LOAD_USERINFO_REQUEST = '/auth/REQUEST_LOAD_USERINFO';
export const LOAD_USERINFO_SUCCESS = '/auth/SUCCESS_LOAD_USERINFO';
export const LOAD_USERINFO_ERROR = '/auth/ERROR_LOAD_USERINFO';

export const REGISTER_REQUEST = '/auth/REQUEST_REGISTER';
export const REGISTER_SUCCESS = '/auth/SUCCESS_REGISTER';
export const REGISTER_ERROR = '/auth/ERROR_REGISTER';

export const CHANGE_USER_REQUEST = '/auth/REQUEST_CHANGE_USER';
export const CHANGE_USER_SUCCESS = '/auth/SUCCESS_CHANGE_USER';
export const CHANGE_USER_ERROR = '/auth/ERROR_CHANGE_USER';

export const CHANGE_PASSWORD_REQUEST = '/auth/REQUEST_CHANGE_PASSWORD';
export const CHANGE_PASSWORD_SUCCESS = '/auth/SUCCESS_CHANGE_PASSWORD';
export const CHANGE_PASSWORD_ERROR = '/auth/ERROR_CHANGE_PASSWORD';

export const ACTIVATE_USER_REQUEST = '/auth/REQUEST_ACTIVATE_USER';
export const ACTIVATE_USER_SUCCESS = '/auth/SUCCESS_ACTIVATE_USER';
export const ACTIVATE_USER_ERROR = '/auth/ERROR_ACTIVATE_USER';

export const RESET_PASSWORD_REQUEST = '/auth/REQUEST_RESET_PASSWORD';
export const RESET_PASSWORD_SUCCESS = '/auth/SUCCESS_RESET_PASSWORD';
export const RESET_PASSWORD_ERROR = '/auth/ERROR_RESET_PASSWORD';

export const RESET_PASSWORD_CONFIRM_REQUEST = '/auth/REQUEST_RESET_PASS_CONFIRM';
export const RESET_PASSWORD_CONFIRM_SUCCESS = '/auth/SUCCESS_RESET_PASS_CONFIRM';
export const RESET_PASSWORD_CONFIRM_ERROR = '/auth/ERROR_RESET_PASS_CONFIRM';

export const LOGOUT_SUCCESS = '/auth/LOGOUT_SUCCESS';

export const RESET_PASSWORD_CONFIRM = '/auth/RESET_PASSWORD_CONFIRM';
export const RESET_PASSWORD = '/auth/RESET_PASSWORD';
export const CHANGE_PASSWORD = '/auth/CHANGE_PASSWORD';
export const CHANGE_USER = '/auth/CHANGE_USER';
export const ACTIVATE_USER = '/auth/ACTIVATE_USER';
export const REGISTER_USER = '/auth/REGISTER_USER';
export const LOGIN_USER = '/auth/LOGIN_USER';
export const LOGOUT = '/auth/LOGOUT';
export const CHECK_USER_AUTH = '/auth/CHECK_USER_AUTH';
